package:
  name: average_entropy
  version: "1.0.0"

source:
  path: ../

build:
  noarch: python
  script: python setup.py install
  # script: python setup_conda.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python

about:
  license: GNU GENERAL PUBLIC LICENSE
  summary: "XXX"
